model_type: "openpi"

# Model path - should be set in specific config files
model_path: "/path/to/model/openpi"

precision: null # for openpi, precision is null, please do not change this value

# Action and chunk settings
num_action_chunks: 10
action_dim: 7

# Training settings
use_proprio: True
num_steps: 5

# openpi specific parameters
openpi:
  model_class_name: "OpenPi0ForDSRL"
  pi05: True
  config_name: "pi05_libero"
  num_images_in_input: 2
  action_horizon: 10
  action_chunk: ${model.num_action_chunks}
  num_steps: ${model.num_steps}
  train_expert_only: True
  action_env_dim: ${model.action_dim}
  discrete_state_input: False
  # DSRL-specific
  dsrl_state_dim: 8
  dsrl_action_noise_dim: 32
  dsrl_num_q_heads: 10
  dsrl_image_latent_dim: 64
  dsrl_state_latent_dim: 64
  dsrl_hidden_dims: [128, 128, 128]
  dsrl_action_magnitude: 1.0

data:
  name: "libero"
  repo_id: "physical-intelligence/libero"
  prompt_from_task: True
  assets_dir: "checkpoints/torch/pi0_libero/assets"
  extra_delta_transform: False
