defaults:
  - envs/libero_10@env.train
  - envs/libero_10@env.eval
  - models/pi05_for_rlt@model

hydra:
  run:
    dir: outputs/${runner.logger.experiment_name}/${now:%Y-%m-%d_%H-%M}

algorithm:
  policy_class: rlt
  agg_reward: max

  # TD3 hyperparameters
  gamma: 0.990045  # 0.999 ** 10 (num_action_chunks)
  tau: 0.005
  agg_q: redq
  critic_actor_ratio: 2
  rlt_alpha: 1.0

  # Training
  utd_ratio: 1.0
  global_warmup_steps: 1000
  global_replay_buffer_size: 100000
  global_batch_size: 512
  micro_batch_size: 128
  queue_size: 4

  # Rollout
  rollout_epochs: 1
  eval_rollout_epochs: 25

env:
  env_client_host: "localhost"
  env_client_base_port: 5550
  train:
    seed: ${runner.seed}
    total_num_envs: 64
    max_episode_steps: 480
    reward_coef: 1.0
    use_rel_reward: False
    use_step_penalty: True
  eval:
    seed: ${runner.seed}
    total_num_envs: 20
    max_episode_steps: 480
    group_size: 1
    is_eval: True
    use_step_penalty: True
    use_rel_reward: False

model:
  model_path: "$SCRATCH/RLinf-Pi05-LIBERO-SFT"
  num_action_chunks: 10
  action_dim: 7
  use_proprio: True
  num_steps: 5

  openpi:
    config_name: "pi05_libero"
    num_images_in_input: 2
    action_horizon: 10
    # RLT-specific
    rlt_state_dim: 8
    rlt_hidden_dims: [512, 512, 512]
    rlt_num_q_heads: 10
    rlt_ref_action_dropout: 0.5
    rlt_action_magnitude: 1.0

  data:
    name: "libero"
    repo_id: "physical-intelligence/libero"
    prompt_from_task: True
    assets_dir: "/scratch/s/sunyh/RLinf-Pi05-LIBERO-SFT"
    extra_delta_transform: False

training:
  optim:
    lr: 1.0e-4
    value_lr: 3.0e-4
    clip_grad: 3.5
    critic_clip_grad: 10.0

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False
    forward_prefetch: False
    backward_prefetch: null
    mixed_precision:
      param_dtype: ${model.precision}
      reduce_dtype: ${model.precision}
      buffer_dtype: ${model.precision}

runner:
  seed: 42
  max_epochs: 500
  eval_interval: 10
  save_interval: 10
  resume_from: null
  is_debug: False
  logger:
    project: "VLARLKit"
    experiment_name: "libero_10_rlt_pi05"
